server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: jpa

  flyway:
    enabled: false

logging:
  level:
    root: INFO
    pl:
      futurecollars:
        invoicing.db: DEBUG