server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: memory
  flyway:
    enabled: false
  security:
    user:
      name: marta
      password: abc123

logging:
  level:
    root: INFO
    pl:
      futurecollars:
        invoicing.db: DEBUG