spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing-jpa
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false

invoicing-system:
  database: jpa