package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import pl.futurecollars.invoicing.db.WithId;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class Company implements WithId {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Company id (generated by application)", required = true, example = "1")
    private Long id;

    @Column(name = "tax_identification_number")
    @ApiModelProperty(value = "Tax identification number", required = true, example = "666-666-69-69")
    private String taxIdNumber;

    @ApiModelProperty(value = "Company address", required = true, example = "ul. Żwirki i Wigury 80, 87-100 Toruń")
    private String address;

    @ApiModelProperty(value = "Name of Company", required = true, example = "Radio Szatan. Głos szatana w Twoim domu xD")
    private String name;

    @Builder.Default
    @ApiModelProperty(value = "Health insurance amount", required = true, example = "1567.99")
    private BigDecimal healthInsurance = BigDecimal.ZERO;

    @Builder.Default
    @ApiModelProperty(value = "Pension insurance amount", required = true, example = "662.01")
    private BigDecimal pensionInsurance = BigDecimal.ZERO;
}
